### ISSUE TITLE
Face Import fixups

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#196]
At best this will prove just a docs fixups
At worst...

- [ ] add info on the docs on how to export a jpg for Bash to show as preview
- [ ] did the class checkbox ever display anything ?
- [ ] regression on import face from save to save
- [ ] verify the rest works (mod to mod, mod to save)

**Comment by AndalayBay** [comment]
Tested face import using saved game files.
First test attempt to change name and gender on import. The characters had different names, but we the same race and gender. The source character is level 16 and the game I imported to was a level 1 character. This test crashed on import:
`Traceback (most recent call last):`
`  File "bash\basher\dialogs.py", line 347, in DoImport`
`    bosh.PCFaces.save_setFace(self.fileInfo,self.data[item],flags)`
`  File "bash\bosh.py", line 8842, in save_setFace`
`    PCFaces.save_setPlayerFace(saveFile,face,flags)`
`  File "bash\bosh.py", line 8964, in save_setPlayerFace`
`    buff.write(postName)`
`  File "D:\Python27\lib\StringIO.py", line 230, in write`
`    self.buf += ''.join(self.buflist)`
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xcb in position 6: ordinal not in range(128)`

Second attempt didn't change anything and that worked fine. During my tests, I tried the imports with the saved game files in the  same directory and with them in different directories - both worked fine as long as I didn't try to change anything on import.

**Comment by Utumno** [comment]
Thanks - just use triple \` to surround code blocks.

This error is a Unicode error - what was the name of the character

**Comment by Utumno** [comment]
> Edit: Found the details for creating an image. Is the path still and name still Data\Docs\Images\[EditorID].jpg?

yep IIUC - what are the details ?

**Comment by AndalayBay** [comment]
Character's name is Soren in the current game and Soren Renard in the game I was exporting the face from.
You just take a screenshot of the character either in the game or the CS, depending on where you created him. Trim it down to just the face, save it as a JPG and put it in that directory. To get the Editor ID, just set debug text (sdt) to 9 in the console, then toggle debug text (tdt). If you don't have anything else selected, it will show the details of your character at the top of the screen and you can grab the editor ID. If you do have something selected, click on the object while the console is open and it will switch to your character. Rename the file to something like Images58001234.jpg, where the digits are the editor ID.
Apologies if all this is old hat - I'm not making any assumptions. :)

**Comment by AndalayBay** [comment]
Images don't seem to work for saved game files, which isn't a surprise really. The character is Soren00000007, so I tried changing the image file names to Images00000007.jpg. I don't think it's a surprise since the saved game file might be in a completely different directory, so how would WB know where to grab the image from? I tried copying the images into the images directory for the target game, but that didn't work either.

**Comment by Utumno** [comment]
Well the code for it is here: https://github.com/wrye-bash/wrye-bash/blob/7e085d79644138ae83f80adc847ca48deefd8461/Mopy/bash/basher/dialogs.py#L323-L326

Adding a print I got (for Lyana Anmel - @leandor's char :D)

    C:\GAMES\TESIV3\Oblivion\Data\Docs\Images\00000007 Lyanna Amnell.jpg


Sure enough:

![clipboard01](https://cloud.githubusercontent.com/assets/1365079/6885485/71e37c54-d622-11e4-852f-3bd3c22a9b8d.jpg)

What confused me is the comment here: https://github.com/wrye-bash/wrye-bash/blob/7e085d79644138ae83f80adc847ca48deefd8461/Mopy/bash/basher/mod_links.py#L1668-L1675
in the import code. It seems that bassh could actually export the face to a jpeg ?

**Comment by Utumno** [comment]
Ok fixed the name importing thing (and left the printing of the path that Bash expects in)

306.201503291746, usual place

Great opportunity to test delete also I will soon merge to dev - especially check if deleting an ini tweak, mod etc correctly updates BAIN

@AndalayBay: The installers tab is not asking for confirmation on delete cause you have apparently disabbled delete confirmation on sending a file in the recycling bin - right ?

**Comment by AndalayBay** [comment]
Could you fix the documentation a bit for the character image? When it said [editorID].jpg, I thought that's exactly what it meant. I'll try renaming my files, although it's still not clear to me how it would retrieve the image when you're importing from a saved game file, especially if the file is in a completely separate directory. I use mTES4, so I'm using a save from another game instance.

Yes, you are correct about the recycle bin. If that's the case, that's fine. I actually prefer not to be prompted.

**Comment by AndalayBay** [comment]
Ok, now I see what you're doing. The message on face import is:
```
D:\Games\Oblivion\Data\Docs\Images\00000007 Soren Renard.jpg
```
However the saved game file that has the face is *My Games\Oblivion-mTES4\DD OBSE 21 Mod Dev 2\Saves\Save 1828 - Soren Renard - Black Marshes, Level 16, Playing Time 170.26.34.ess*

Not a surprise that it wouldn't be able to find the image. So if I copy an image to the destination game matching that name, I would see it on import.

**Comment by Utumno** [comment]
>  So if I copy an image to the destination game matching that name, I would see it on import.

Hopefully :)

Yeah the docs - once it functions

Actually once all is done I'll be accepting docs patches ;)

**Comment by leandor** [comment]
I've been doing some tests with the last snapshot (5c697c0dd88980bf3341d2245a04cce7660a67b2) and for all I could see it seems to be working perfectly. 

I was able to test this scenario, using the original face I've uploaded before.

1. New Mod "Original Face.esp" for importing faces (so I can test import to ESP)
2. Add Masters needed for the face (In my case bgBalancingCoreEV.esp)
3. Import face from original save to mod
4. Verify with the CS that the face indeed was imported OK.

Then I proceeded to modify the face on the CS, just to check if I can also import it back to a new save. 

So, I did second series of steps for that:

1. Duplicate File for Mod Original Face -> Edited Face.esp
2. Add New masters required for the load order (Oblivion Character Overhaul and the patch for RBP-OCO... needed to be able to see the hairs/eyes from RBP on the races edited by OCO)
3. Went to CS again (now with the added masters, face looks different...) to edit the face.
4. Tweaked the face to look good on OCO
 * Took screenshots from the CS facegen and saved them to Docs\Images\<EditorId>.jpg as Bash docs said.
5. Started game and select new game -> create new PC "Test" with same race/gender and finish. Close game.
6. In bash again, Import face from Edited Face.esp to newly created savegame. Untick all options .
 * Bash shows in the preview the screenshot I saved in 4.1
7. Launch game and verify: face imported **successfully**

Would you want a more detailed procedure, with screenshots and all for documentation?

**Comment by Utumno** [comment]
Thanks @leandor - will get back to you ASAP - would be nice to link here to the test material and the procedure

Quick questions:
- does "class" work ?
- did Bash _ever_ have the ability to export a face _image_ from a save ?
- esp to esp ?
- all those tests were with only face ? Name should work - the rest probably too ?

Thanks :)

<Meanwhile if you can edit html could you go through the readme and edit any inaccuracies ?>

**Comment by leandor** [comment]
Good points! I'll try to test them sometime todayish (later in the evening...) or tomorrow after work, if I'm not able to get to it today.

As for the image, in my tests, Bash it generated an image as a copy of the savegame screenshot when I did the transfer from save to ESP.

[Here's the link](https://drive.google.com/folderview?id=0B9lns9afVHMcMXl3T2ZnTUZFczQ&usp=sharing) to the folder where I've put the original files I used as test. Still haven't updated them with new changes, but I'll get to it today or tomorrow too.

And yes, in my previous tests Class import did work. Didn't tested that this last time, but I'll get to it too.

Here's the full procedure I used for testing the import (copied from the old ticket) from Save to Save:
```
1. start with test save that is clean with a new character created 
 (same gender and race as the original one)
2. Start bash (at revision x where x changes in each step) and 
 do File -> Duplicate and give the new file a name that doesn't 
 overwrite existing previous tests.
3. Use File -> Import Face and select the original save with 
 the real char that has the face you want to import
4. Fill the options in the import window -> I use all options ticked, 
 except the name as it doesn't seems to work
5. Check that the new save masters were altered correctly 
 (master bgBalancingEVCore.esp is added... 
 this doesn't happen with the version on which the import do not work)
6. Start the game and load the new save game... 
 check character face and verify that import indeed worked.
```

And this is the procedure used to tests the import from Save to Plugin:
```
1. On the Mods tab: File -> New Mod
2. Select New Mod.esp -> Right click then Add Master -> Select bgBalancingEVCore.esp
3. Again, on New Mod.esp -> Right click then Import Face -> Select origin ESS
4. Tick the mod in the LO
5. Start the CS and load New Mod as active plugin.
6. Search for NPC, name starting with 'sg'
7. Edit -> opens NPC edit window
8. Immediately click 'Full Preview' -> NPC should draw in full body
9. Click HEAD -> preview of the head shown.
```

**Comment by Utumno** [comment]
Thanks indeed - take your time I am pressed with 306 anyway :)

**Comment by leandor** [comment]
Sorry I couldn't get to this yet :( Will try to get my hands on these tests on this coming week. I'll keep you posted!

**Comment by rafaelalcid** [comment]
Hi!

After I update my Bash, I can't import my face from my previous save anymore (but when I install and older version, it does normally.
Here's the error message:

Traceback (most recent call last):
  File "bash\balt.pyo", line 1839, in __Execute
  File "bash\balt.pyo", line 884, in _conversation_wrapper
  File "bash\basher\saves_links.pyo", line 257, in Execute
  File "bash\bosh\faces.pyo", line 106, in save_getFaces
  File "bash\bosh\faces.pyo", line 181, in save_getPlayerFace
AttributeError: 'SaveFile' object has no attribute 'pcName'

Could you guys help me??

**Comment by Infernio** [comment]
Is that with 308 or with the latest WIP build? Link to that build is in the second post in the AFKMods thread or on out Discord.

**Comment by rafaelalcid** [comment]
> 
> Is that with 308 or with the latest WIP build? Link to that build is in the second post in the AFKMods thread or on out Discord.
> […](#)
> On 4. Apr 2021, at 00:55, rafaelalcid ***@***.***> wrote: ﻿ Hi! After I update my Bash, I can't import my face from my previous save anymore (but when I install and older version, it does normally. Here's the error message: Traceback (most recent call last): File "bash\balt.pyo", line 1839, in __Execute File "bash\balt.pyo", line 884, in _conversation_wrapper File "bash\basher\saves_links.pyo", line 257, in Execute File "bash\bosh\faces.pyo", line 106, in save_getFaces File "bash\bosh\faces.pyo", line 181, in save_getPlayerFace AttributeError: 'SaveFile' object has no attribute 'pcName' Could you guys help me?? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

308, from Nexus.

**Comment by Infernio** [comment]
In that case, try again with [the WIP build](https://www.dropbox.com/sh/gfz6ga6ctuduj6j/AACmPrgl_JPI63z8RZ6esfW0a?dl=0).

**Comment by rafaelalcid** [comment]
> 
> 
> In that case, try again with [the WIP build](https://www.dropbox.com/sh/gfz6ga6ctuduj6j/AACmPrgl_JPI63z8RZ6esfW0a?dl=0).

Which one? there are 3 of them, lol.
What's 'WIP'?
Thank you very much!

**Comment by Infernio** [comment]
WIP = Work In Progress, the 3 versions are installer, standalone and python. If you usually use the installer, use the installer here too; if you usually use the standalone, use the standalone here too, etc.

**Comment by rafaelalcid** [comment]
> 
> 
> In that case, try again with [the WIP build](https://www.dropbox.com/sh/gfz6ga6ctuduj6j/AACmPrgl_JPI63z8RZ6esfW0a?dl=0).

Which one? there are 3 of them, lol.
What's 'WIP'?
Thank you very much!

> 
> 
> WIP = Work In Progress, the 3 versions are installer, standalone and python. If you usually use the installer, use the installer here too; if you usually use the standalone, use the standalone here too, etc.

Ah!

Thanks, Infernio!!

**Comment by rafaelalcid** [comment]
> 
> 
> In that case, try again with [the WIP build](https://www.dropbox.com/sh/gfz6ga6ctuduj6j/AACmPrgl_JPI63z8RZ6esfW0a?dl=0).

It's working!
Thanks a lot, Infernio!
