### ISSUE TITLE
Factor out environment specific stuff

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#258]
... to an `env.py` module. This should be very high in import order, ~~certainly above bolt~~ as it is now I import Path,GPath so....
Started working on it on my bleeding edge branch: https://github.com/wrye-bash/wrye-bash/commit/ecd9b1690723bfe84ab1e86df3587b4cf8330878

This will evolve to have linux also versions of its functions - a necessary step towards #243

**Comment by Utumno** [comment]
Closing thsi for now as most of it was done in https://github.com/wrye-bash/wrye-bash/commit/646df2ca063c2dff03cb2185e7e2969fdea065a5

Remains win32api - some console stuff:

```
win32api

>>> import win32api
>>> import os
>>> os.getcwd()
'C:\\Dropbox\\eclipse_workspaces\\python\\wrye-bash'
>>> win32api.GetFileVersionInfo('Mopy')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: GetFileVersionInfo() takes exactly 2 arguments (1 given)
>>> win32api.GetFileVersionInfo('Mopy', u'\\')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
error: (2, 'GetFileVersionInfo:GetFileVersionInfoSize', 'The system cannot find the file specified.')

>>> try: win32api.GetFileVersionInfo('Mopy', u'\\')
... except Exception as e: print e
(2, 'GetFileVersionInfo:GetFileVersionInfoSize', 'The system cannot find the file specified.')
>>> try: win32api.GetFileVersionInfo('Mopy', u'\\')
... except Exception as e: print e.__class__
<class 'pywintypes.error'>
>>> import pywintypes
>>> try: win32api.GetFileVersionInfo('Mopy', u'\\')
... except pywintypes.error as e: print e.__class__
<class 'pywintypes.error'>
>>> os.listdir('.')
['.git', '.gitattributes', '.gitignore', '.idea', '.settings', '.__', 'BashBugDump.log', 'Mopy', 'PYCHARM READ ONLY.txt', 'Readme.md', 'scripts']
>>> win32api.GetFileVersionInfo('Readme.md', u'\\')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
error: (1812, 'GetFileVersionInfo:GetFileVersionInfoSize', 'The specified image file did not contain a resource section.')
>>> try: win32api.GetFileVersionInfo('Mopy/Wrye Bash.exe', u'\\')
... except pywintypes.error as e: print e.__class__
{u'FileFlagsMask': 63, u'FileType': 1, u'FileVersionMS': 43646976, u'FileVersionLS': 0, u'Signature': -17890115, u'FileSubtype': 0, u'FileFlags': 0, u'ProductVersionLS': 1, u'FileDate': None, u'ProductVersionMS': 65536, u'FileOS': 262148, u'StrucVersion': 65536}
>>> win32api.GetFileVersionInfo('Mopy/Wrye Bash.exe', u'\\')
{u'FileFlagsMask': 63, u'FileType': 1, u'FileVersionMS': 43646976, u'FileVersionLS': 0, u'Signature': -17890115, u'FileSubtype': 0, u'FileFlags': 0, u'ProductVersionLS': 1, u'FileDate': None, u'ProductVersionMS': 65536, u'FileOS': 262148, u'StrucVersion': 65536}
```

**Comment by Infernio** [comment]
[Started an attempt at tackling this.](https://github.com/wrye-bash/wrye-bash/tree/inf-258-env-package) Still far from finished, the shell stuff is (unsurprisingly) proving to be the hardest bit to untangle. I also can't test it on Linux right now because my distro dropped py2 support, so I'll have to build a wxPython 4.1 for py2 myself. Will get to it tomorrow.
