### ISSUE TITLE
Version 307: Mark Mergeable (CBash and normal) on unmergeable plugin reports error instead of dialogue box

### ISSUE THREAD

**Issue by jatkinson85** [wrye-bash/wrye-bash#284]
When trying to "mark mergeable" my load order or any plugin not currently marked as mergeable instead of getting the box giving reasons why it's not mergeable I get the following error:
 
Traceback (most recent call last):
  File "bash\balt.pyo", line 2351, in __Execute
  File "bash\balt.pyo", line 1574, in _conversation_wrapper
  File "bash\basher\mod_links.pyo", line 807, in Execute
  File "bash\basher\__init__.pyo", line 892, in RefreshUI
  File "bash\balt.pyo", line 1799, in RefreshUI
  File "bash\balt.pyo", line 1723, in PopulateItem
  File "bash\basher\__init__.pyo", line 778, in <lambda>
AttributeError: 'unicode' object has no attribute 's'
 
This occurs for either the Cbash or normal version of "Mark Mergeable"

**Comment by Utumno** [comment]
Good catch there - consider posting me the bugdump when reporting an error although this is good enough for this one

**Comment by jatkinson85** [comment]
Thanks for the reply :).  Where is the bugdump located for future reference?

**Comment by Utumno** [comment]
https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug
