### ISSUE TITLE
Wizard for Surazel's Sensual Walks 8.42 fails to initialize and throws error (307)

### ISSUE THREAD

**Issue by jatkinson85** [wrye-bash/wrye-bash#285]
When attempting to run the wizard for [Surazel's Sensual Walks 8.42](http://www.nexusmods.com/oblivion/mods/28223/?) if fails and produces this error:

An unhandled error occurred while parsing the wizard:
Line 17:    If CompareWBVersion(292) < 0

Traceback (most recent call last):
  File "bash\belt.pyo", line 932, in Continue
  File "bash\ScriptParser.pyo", line 500, in RunLine
  File "bash\ScriptParser.pyo", line 365, in **call**
  File "bash\ScriptParser.pyo", line 286, in **call**
  File "bash\ScriptParser.pyo", line 574, in ExecuteTokens
  File "bash\ScriptParser.pyo", line 707, in ExecuteRPN
  File "bash\ScriptParser.pyo", line 365, in **call**
  File "bash\ScriptParser.pyo", line 242, in **call**
  File "bash\ScriptParser.pyo", line 259, in execute
  File "bash\belt.pyo", line 1123, in fnCompareWBVersion
ValueError: invalid literal for float(): 307.2016.0316.0248

I think it fails because it's expecting whole number versions of Wrye Bash.  I'll try reverting to 306 and see if this fixes the issue.

Edit:

Reverting to 306 does indeed fix the issue.

**Comment by Utumno** [comment]
Ok this is a catch of using the version numbering I use - good point but please do not post an issue for everything you come across cause some things such as this do not deserve one - don't get me wrong please ;)

In general I prefer you post in the forums first to investigate and then I will ask you as I did for the cbash one to post it here if needed - issues are for things that may require serious effort and may not be immediately fixed - even the #284 you posted should be brought up in the forums cause it's just an easy fix introduced on the development version.

Again don't get me wrong but bear in mind that the time I can devote to Bash is this much and issues can be a serious distraction. So please post in the forums first :)

**Comment by Utumno** [comment]
Not a bug but still relevant to #260 versioning scheme - we should put in bass nothing but a float !

Reopening to close from commit.
