### ISSUE TITLE
Error with utumno-wip and Skyrim mode

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#331]
@Utumno I get an error trying to build a bash patch for Skyrim.

``` Python
Traceback (most recent call last):
  File "bash\balt.py", line 2395, in __Execute
    self.Execute()
  File "bash\balt.py", line 1550, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\mod_links.py", line 873, in Execute
    if not self._Execute(): return # prevent settings save
  File "bash\basher\mod_links.py", line 957, in _Execute
    importConfig) as patchDialog:
  File "bash\basher\patcher_dialog.py", line 86, in __init__
    patcher.getConfig(patchConfigs) #--Will set patcher.isEnabled
  File "bash\basher\gui_patchers.py", line 474, in getConfig
    self.getAutoItems() # calls get_set_choice which sets default
  File "bash\basher\gui_patchers.py", line 506, in getAutoItems
    autoItems = self._get_auto_mods()
  File "bash\basher\gui_patchers.py", line 524, in _get_auto_mods
    if self.choiceMenu: self.get_set_choice(name)
NameError: global name 'name' is not defined
```

If I look at the offending code I see this.

![wryeskyerror](https://cloud.githubusercontent.com/assets/1912426/19301901/a3dd7bc4-9016-11e6-9684-5fb73a38a453.jpg)

If I add something like name = mod.name then I get this error.

``` Python
Traceback (most recent call last):
  File "bash\balt.py", line 2395, in __Execute
    self.Execute()
  File "bash\balt.py", line 1550, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\mod_links.py", line 873, in Execute
    if not self._Execute(): return # prevent settings save
  File "bash\basher\mod_links.py", line 957, in _Execute
    importConfig) as patchDialog:
  File "bash\basher\patcher_dialog.py", line 86, in __init__
    patcher.getConfig(patchConfigs) #--Will set patcher.isEnabled
  File "bash\basher\gui_patchers.py", line 474, in getConfig
    self.getAutoItems() # calls get_set_choice which sets default
  File "bash\basher\gui_patchers.py", line 506, in getAutoItems
    autoItems = self._get_auto_mods()
  File "bash\basher\gui_patchers.py", line 521, in _get_auto_mods
    name = mod.name
AttributeError: 'Path' object has no attribute 'name'
```

So I changed it to [if self.choiceMenu: self.get_set_choice(mod.s)](https://github.com/wrye-bash/wrye-bash/blob/utumno-wip/Mopy/bash/basher/gui_patchers.py#L524) then it works but I don't know if that's correct or not.

**Comment by Utumno** [comment]
Thanks but please do not post issues on utumno-wip, that's not stable code - post in the forums instead that's where the wips are discussed. Or you can add a comment in the tip of urtumno-wip here - although the forums are preferred so other people get notified too, plus the less noise here the better (plus comments I think pin the commit and all its parents of course in github bloating the upstream repo, IIRC)

I am actively refactoring the patchers code in my wip so I don't want to push the fixed branch (still fixing stuff there, for instance just realized race patcher checkbox selections never worked) - but the correct thing to do is change it to `if self.choiceMenu: self.get_set_choice(mod)` mod is a boltPath (very central class) and mod.s is the string in the path

Use that workaround till I merge the new wip

Try using the debugger and set breakpoints - there is a learning curve but it will really really save you time in the end :)

**Comment by Utumno** [comment]
And just some more: modInfos.values are ModInfo (check that class) they have a name attribute. ModInfos is a dict containing mod (bolt.Path) -> ModInfo pairs
