### ISSUE TITLE
Wrye Bash Launch failure

### ISSUE THREAD

**Issue by Vaeret** [wrye-bash/wrye-bash#348]
Hello,
I was trying to install Wrye Bash v 306 Stand alone version for the fist time on my computer, but it seems to crash at launch with following error

testing UAC
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.pyo", line 382, in main
  File "bash\bash.pyo", line 364, in main
  File "bash\bosh.pyo", line 10441, in initBosh
  File "bash\bosh.pyo", line 10240, in initDirs
  File "bash\bosh.pyo", line 5247, in __init__
  File "bash\bosh.pyo", line 5278, in refreshBashTags
  File "bash\loot.pyo", line 334, in Load
  File "bash\loot.pyo", line 231, in LootErrorCheck
bash.bolt.BoltError: An error occurred while parsing taglist.yaml with the LOOT API: LootError: loot_error_parse_fail:'utf8' codec can't decode byte 0xd1 in position 21: invalid continuation byte

The system version is Win 7 x64 . I installed Wrye Bash through installer and intended to use it for Oblivion (retail copy). I belive that i installed it correctly because i was following the installation guide step by step. Also i use LOOT v 0.10.1. All programs are installed in D:/Oblivion directory as was reccomended in guides and at forums.
I tried to look for similar errors in the web but could find the one that maches mine. Can somebody help me to understand what can possibly cause the erorr? Thanks in advance.

**Comment by Utumno** [comment]
Please install v307 pre beta from https://www.dropbox.com/sh/7b5ily482re0khs/AAD3vAWMVJNIpuS30tsdVte5a?dl=0

**Comment by Utumno** [comment]
Closing as needinfo - probably fixed in 307

**Comment by Vaeret** [comment]
Thank you, new version solved the problem
