### ISSUE TITLE
Refresh Optimizations II

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#353]
Now that the severe performance issues are addressed (#123, #205, #247 etc etc) it's high time we had the refresh APIs reworked as already discussed in commit messages and other issues here. Opening this to have commits refer to a common issue and to start investigating. In short:

- more granular refreshes (avoid refreshing the whole list or rescanning the data dir when we know what changed):
  - [x] RefreshUI should accept deleted, modified (currently files) and added parameters and act accordingly (https://github.com/wrye-bash/wrye-bash/commit/f65b068b26c0c89b3707be677a5b06abca14e4cc)
  - [ ] Same goes double for refresh()
- [x] BAIN RefreshUIMods should be made aware of bsas -> c6ec3997e3ef26ac350c47933567602ffdfc02e3
- [ ] prune all refresh() calls outside the data model -> edit 11/2023 rather prune refresh satellites (delete_refresh...) and clearly mark cached_lo methods that do refresh
- [ ] RefreshUI details (81cacb1d72e4cd4213fc0d8fd3d21cc2e03d9f06) and selection handling parameters
- [ ] ShowPanel (->RefreshPanel) API reworking to pass on the parameters to refresh/ui - also comment it and clean it up to be used everywhere
- [ ] investigate scanning Data folder once  - we scan for BAIN, bsas, mods... (4101778bf4bbaa69ad8597bc284cb507f4933f09 )
  - [ ] As an extension of this, we should have one central place where we can dump an update (i.e. something like `handle_changed(added, updated, deleted)`) which then propagates to the right handlers (ModInfos, BSAInfos, etc.) instead of us having to do that manually - this will enable #265
- [ ] in BAIN refreshTracked we should pass the changed crc, size, mtime in instead of recalculating them - see ebbdc79cb7cbcfe5a90525a332892bb16ff54340

This is not so much for performance (although scanning the data dir and redrawing all items _is_ measurable performance) as for code stability and maintainability and elegance.

Plus blocks #265 - we can't switch to an event based model without robust deletion/addition/modification handlers

**Comment by Infernio** [comment]
Traceback I just got from installing and uninstalling a package (not sure which part triggered it):

```
Traceback (most recent call last):
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/gui/events.py", line 181, in _post
    result = listener(*listener_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/balt.py", line 515, in _conversation_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/basher/__init__.py", line 4005, in RefreshData
    store.unique_store_key: not booting and bool(store.refresh()) # todo add the refr object here
                                                 ^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bosh/__init__.py", line 2399, in refresh
    rdata = super().refresh(booting=booting) if refresh_infos else \
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bosh/__init__.py", line 1657, in refresh
    new_or_present, del_infos = self._list_store_dir()
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bosh/__init__.py", line 1711, in _list_store_dir
    return self._diff_dir(FNDict(((x, {}) for x in inodes)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bosh/__init__.py", line 2387, in _diff_dir
    return super()._diff_dir(FNDict(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bosh/__init__.py", line 1724, in _diff_dir
    if (cor := self.corrupted.get(k)) and cor.do_update():
                                          ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'do_update'
```
