### ISSUE TITLE
[307.201705181249] Creating a patch or blank plugin throws errors

### ISSUE THREAD

**Issue by pabulum547** [wrye-bash/wrye-bash#374]
I always get this error when I try to create the patch or blank plugin. If I have the .ini setting for creating one automatically when it launches , it will throw the error window briefly and quit.

```
[BASHED PATCH]
Wrye Bash starting
Using Wrye Bash Version 307.201705181249
OS info: Windows-8.1-6.3.9600
Python version: 2.7.13
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: UTF8; output encoding: None; locale: ('en_US', 'cp1252')
filesystem encoding: mbcs 
bash.py  322 main: Searching for game to manage:
bush.py   89 __supportedGames: Detected the following supported games via Windows Registry:
bush.py   91 __supportedGames:  Oblivion: E:\SteamLibrary\steamapps\common\Oblivion
bush.py   91 __supportedGames:  Skyrim: E:\SteamLibrary\steamapps\common\Skyrim
bush.py   91 __supportedGames:  Skyrim Special Edition: E:\SteamLibrary\steamapps\common\Skyrim Special Edition
bush.py   91 __supportedGames:  Fallout4: E:\SteamLibrary\steamapps\common\Fallout 4
bush.py  149 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.py  155 _detectGames: Set game mode to Skyrim based on sOblivionPath setting in bash.ini:  E:\SteamLibrary\steamapps\common\Skyrim
bush.py  170 __setGame:  Using Skyrim game: E:\SteamLibrary\steamapps\common\Skyrim
testing UAC
mods_metadata.py  224 __init__: Using LOOT API version: 0.10.2
Traceback (most recent call last):
  File "bash\balt.py", line 2490, in __Execute
    self.Execute()
  File "bash\basher\mods_links.py", line 220, in Execute
    self.window.GetSelected())
  File "bash\bosh\__init__.py", line 2457, in generateNextBashedPatch
    masterless=True, bashed_patch=True)
  File "bash\bosh\__init__.py", line 2440, in create_new_mod
    newFile.safeSave()
  File "bash\parsers.py", line 4056, in safeSave
    filePath.temp.mtime = self.fileInfo.mtime
  File "bash\bolt.py", line 824, in _setmtime
    os.utime(self._s, (self.atime, int(mtime)))
TypeError: int() argument must be a string or a number, not 'NoneType'
```
```
[BLANK MOD]
Wrye Bash starting
Using Wrye Bash Version 307.201705181249
OS info: Windows-8.1-6.3.9600
Python version: 2.7.13
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: UTF8; output encoding: None; locale: ('en_US', 'cp1252')
filesystem encoding: mbcs 
bash.py  322 main: Searching for game to manage:
bush.py   89 __supportedGames: Detected the following supported games via Windows Registry:
bush.py   91 __supportedGames:  Oblivion: E:\SteamLibrary\steamapps\common\Oblivion
bush.py   91 __supportedGames:  Skyrim: E:\SteamLibrary\steamapps\common\Skyrim
bush.py   91 __supportedGames:  Skyrim Special Edition: E:\SteamLibrary\steamapps\common\Skyrim Special Edition
bush.py   91 __supportedGames:  Fallout4: E:\SteamLibrary\steamapps\common\Fallout 4
bush.py  149 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.py  155 _detectGames: Set game mode to Skyrim based on sOblivionPath setting in bash.ini:  E:\SteamLibrary\steamapps\common\Skyrim
bush.py  170 __setGame:  Using Skyrim game: E:\SteamLibrary\steamapps\common\Skyrim
testing UAC
mods_metadata.py  224 __init__: Using LOOT API version: 0.10.2
Traceback (most recent call last):
  File "bash\balt.py", line 2490, in __Execute
    self.Execute()
  File "bash\basher\mods_links.py", line 243, in Execute
    masterless=self.masterless)
  File "bash\bosh\__init__.py", line 2440, in create_new_mod
    newFile.safeSave()
  File "bash\parsers.py", line 4056, in safeSave
    filePath.temp.mtime = self.fileInfo.mtime
  File "bash\bolt.py", line 824, in _setmtime
    os.utime(self._s, (self.atime, int(mtime)))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

The solution I came up with is to get the beta off Nexus, create the patch through that, store them, and copy them into the data folder when I finish reinstalling the game... again.

**Comment by Utumno** [comment]
Yep - it's fixed on my wip branch: https://github.com/wrye-bash/wrye-bash/tree/utumno-wip
