### ISSUE TITLE
Wyre Bash Installers Tab Problem Oblivion

### ISSUE THREAD

**Issue by Zerckt** [wrye-bash/wrye-bash#383]
So I opened up Wyre Bash and clicked on Installers Tab. It says "Refreshing Installers, Loading Data" and then and error pops up as such:

```
Traceback (most recent call last):
  File "bash\basher\__init__.pyo", line 3536, in OnShowPage
  File "bash\balt.pyo", line 1563, in _conversation_wrapper
  File "bash\basher\__init__.pyo", line 2853, in ShowPanel
  File "bash\balt.pyo", line 1563, in _conversation_wrapper
  File "bash\bosh\__init__.pyo", line 5487, in _projects_walk_cache_wrapper
  File "bash\basher\__init__.pyo", line 2883, in _refresh_installers_if_needed
  File "bash\bosh\__init__.pyo", line 5554, in irefresh
  File "bash\bosh\__init__.pyo", line 5574, in __load
  File "bash\bolt.pyo", line 1465, in load
cPickle.UnpicklingError: invalid load key, '7'.
```

I want to access my Installers, but all I'm left with is with the Mods/ESPs/ESMs even though I selected the Installers Tab. I have Oblivion installed through Steam so it is located in steamapps.
I use Wyre Bash Standalone and I have Windows 8.1 64bit.

**Comment by Sharlikran** [comment]
@Utumno may still request some [additional information](https://github.com/wrye-bash/wrye-bash/wiki/%5Bgithub%5D-Reporting-a-bug). However, the suggestion of renaming or backing up the the setting files I listed on the Oblivion comments section is still one option.  Did you look for the Data (settings) files I mentioned on the Nexus in the Spoiler tag?  The other was to try the latest code.

I forgot to mention on the Nexus that Utumno also likes to refer people to the [second post here](https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=166863).  From that second post you can download the python code from utumno-wip or at the bottom of the post there is a link to the compiled standalone EXE.
