### ISSUE TITLE
Getting this error when trying to run wrye bash through MO2, only just started getting this about a week or two ago    

### ISSUE THREAD

**Issue by Madpaddy** [wrye-bash/wrye-bash#409]
Wrye Bash encountered an error.
Please post the information below to the official thread at:
https://afkmods.com/index.php?/topic/4966-wrye-bash-all-games/& or 
https://bethesda.net/community/topic/38798/relz-wrye-bash-oblivion-skyrim-skyrim-se-fallout-4/

Traceback (most recent call last):
  File "bash\bash.pyo", line 227, in main
  File "bash\bash.pyo", line 393, in _main
  File "bash\basher\__init__.pyo", line 3981, in Init
  File "bash\basher\__init__.pyo", line 4021, in InitData
  File "bash\bosh\__init__.pyo", line 2726, in refresh
  File "bash\bosh\__init__.pyo", line 1382, in refresh
  File "bash\bosh\__init__.pyo", line 1358, in new_info
  File "bash\bosh\__init__.pyo", line 1277, in new_info
  File "bash\bosh\__init__.pyo", line 393, in __init__
  File "bash\bosh\__init__.pyo", line 274, in __init__
  File "bash\bosh\__init__.pyo", line 405, in _reset_cache
  File "bash\bosh\__init__.pyo", line 1108, in readHeader
  File "bash\bosh\save_headers.pyo", line 62, in __init__
  File "bash\bosh\save_headers.pyo", line 78, in load_header
  File "bash\bosh\save_headers.pyo", line 342, in load_image_data
  File "bash\bosh\save_headers.pyo", line 96, in _drop_alpha
MemoryError

**Comment by Utumno** [comment]
We can't debug MO2 errors - you could ask at the threads you linked and maybe someone knows

**Comment by Madpaddy** [comment]
Well its acctually giving that error even if i run it through just windows i think it maybe a windows update that changed something im on windows 10  ver 1803  build 17134.5

**Comment by Arthmoor** [comment]
Build 1803 is 2 days old, you reported this as being more than a week ago. It's definitely an MO2 issue. I'm on Windows 10 1803 now and Wrye Bash runs just fine.

**Comment by Infernio** [comment]
Obsolete as of 308 (64bit upgrade).
