### ISSUE TITLE
[Skyrim SE] Generate Betheada.net file lists from project data.

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#411]
This is a feature request for some future time, but I hope it's simple enough to be something that can be done quickly by someone who knows how these things work.

Uploading a mod to Bethesda.net requires an ESP and BSA pair. Due to a bug in the CK, which Bethesda seems unwilling or unable to fix, that BSA file needs to be manually packed within the CK interface. This can lead to forgetting files and getting wrong files included.

Fortunately the CK also has an option to import a file list that exists from a previous packaging session. These lists are just text files. All they are are path names to files already in the folders, which means that adding a feature to the project menu to make these lists can save a considerable amount of time for SE mod authors who upload to Bethesda.net. I have attached one such file as an example, the one I use to package Cutting Room Floor. It should be more than sufficient to show what needs to be generated and in what format.

The files should be named the same as their plugin file for the mods they go to, and are stored in the Mod Info Exports folder. The filename would be as such for CRF:

"C:\Steam\steamapps\common\Skyrim Special Edition\Mod Info Exports\Cutting Room Floor.achlist"

C:\Steam\steamapps\common\ would obviously be the path to where the user has SSE installed.

Any file found in a folder in the project root should be included.
[Cutting Room Floor.zip](https://github.com/wrye-bash/wrye-bash/files/1990857/Cutting.Room.Floor.zip)

**Comment by Utumno** [comment]
If I understand the attachment right those are all the destination paths in the `Data` dir. Then this boils down to extracting a list of the destination files, should one install the project via BAIN - right?

**Comment by Utumno** [comment]
I added a commit on fallout3/nv branch adding an Export Achlist menu item give that a whirl https://github.com/wrye-bash/wrye-bash/tree/150-fo3-fnv-support

**Comment by Arthmoor** [comment]
Didn't expect this to even be looked at right now but seems to be working.

One problem though is that it's including the ESP file. The plugin files should not be included in the list. I don't know how that being there might affect things.

It would also be helpful for checking against the available resources if it sorted the output in the file alphabetically.

**Comment by Utumno** [comment]
Ok, I pushed a fixed version - I exclude esls esps and esms. The resources added to the achlist are not the entire project folder, just the resources selected for installation. So if you have a complex package it will only add to the achlist the files from the selected subpackages

**Comment by Arthmoor** [comment]
That's fine about the subpackages since Bethesda.net can't do variable install setups anyway. I'll give the new update a go.

**Comment by Arthmoor** [comment]
Looks like the update is good. It pulled all of the needed files from the mods I tested and the alphabetical listing is very much appreciated for easier troubleshooting. I'd say this one is good to go unless there's weird edges cases we haven't thought of.

**Comment by Utumno** [comment]
Could you write a help item I can add to the readme for this new menu - linking also to some definition of those files?

Just for mind-numbing clarity - the list I output is the destinations of the installers files given the current configuration of the installer. It's not the source paths _inside_ the installer - this would take a bit more time to calculate.

**Comment by Utumno** [comment]
Also note that if I understand above correctly I see no reason to limit this in projects.

Should this menu be active only for SSE?

**Comment by Arthmoor** [comment]
Not sure what the distinction is between the destination and source is in this case, the list appears to be properly generated based on the contents of the project folder.

The main reason I suggest using it on projects is that in theory the person using this should also have the mod installed into the Data folder already as it's something being worked on. It's not really suitable for use on regular archives downloaded from Nexus or wherever.

I'd have to double check on it for FO4, but the menu option should only be available for FO4 and SSE.

I'll see about writing up a help entry for it.

**Comment by Arthmoor** [comment]
Fallout 4 uses the same achlist format, so that's good there.

As I said, since this option is for uploading to Bethesda.net, it only makes sense to go by what's currently installed in the project folder. Which in theory should match what BAIN thinks is there or there'd be an orange box or something to tell you it's out of sync.

This should do for the help entry:

Export ACHList

This exports a file list of the contents of a project for use when uploading to Bethesda.net. In the CK, this list is used when the CK asks for a list of files. Import the ACHList Bash generated and it will then package your files into the proper archives for upload. Available only for Skyrim Special Edition and Fallout 4.

**Comment by Utumno** [comment]
Thanks!

As "project folder " I understand the actual folder inside Bash Installers dir - this may be a complex archive that has the same data `data\meshes\foo\bar.nif` in different folders. So what I use is the files configured to be installed by this installer (for simple packages it's the contents of the folder). This has the benefit that changing install options on a complex package will export a different achlist file

**Comment by Arthmoor** [comment]
I see, that makes sense then because you can then make multiple packages of the same thing if you want to and upload them separately to Bethesda.net. So I'd say the feature is working as planned now.

**Comment by Utumno** [comment]
Great I pushed a finalish version with the docs (edited) and also changed the sorting to groups directories together this will make it easier to read I think. Same branch

**Comment by Arthmoor** [comment]
Don't know if it's caused by this last push or something else, but it isn't starting up now. Just getting the following error:

Traceback (most recent call last):
  File "bash\bash.py", line 227, in main
    _main(opts)
  File "bash\bash.py", line 310, in _main
    bush.detect_and_set_game(opts.oblivionPath, bashIni, retCode)
  File "bash\bush.py", line 176, in detect_and_set_game
    __setGame(name, u' Using %(gamename)s game:')
  File "bash\bush.py", line 167, in __setGame
    game.init()
  File "bash\game\skyrimse\__init__.py", line 71, in init
    from .records import MreCell, MreWrld, MreFact, MreAchr, MreDial, \
  File "C:\Wrye Bash 308\Mopy\Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\game\skyrimse\records.py", line 26, in <module>
    from ..skyrim.records import *
  File "C:\Wrye Bash 308\Mopy\Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\game\skyrim\records.py", line 1117, in <module>
    class MreHeader(MreHeaderBase):
  File "bash\game\skyrim\records.py", line 1133, in MreHeader
    __slots__ = MreHeaderBase.__slots__ + melSet.getSlotsUsed()
ImportError: caused by ImportError(u'caused by TypeError(\'can only concatenate tuple (not "list") to tuple\',)',)

**Comment by Utumno** [comment]
No, I have refactored a bit - thanks for testing :P

Should be fixed now

**Comment by Arthmoor** [comment]
Heh, thanks. All good now. I think this achlist ticket can be closed as completed if there's nothing left to check.

**Comment by Sharlikran** [comment]
![image](https://user-images.githubusercontent.com/1912426/42458983-ce1d228a-834f-11e8-86dc-4e77ef6b9ad5.png)

Did you ever have any issues with xEdit exporting that list? If so maybe mention it to @zilav and maybe he can refine it a bit more.

**Comment by Arthmoor** [comment]
I didn't even know xEdit had such a function. The one Utumno wrote up is pretty much there except for picking up ini fragments it's not supposed to and it's pretty straightforward to use.

It's been rather helpful - found several dumb mistakes in some of my mods where files either got left out or added when they shouldn't have been. Which is exactly what I was hoping for.

I'll take a look at the one in xEdit and compare what it returns vs what Bash is returning now.

**Comment by Arthmoor** [comment]
Right, so the xEdit function dumps far too much information about assets the mod merely uses but does not supply itself. That's not very useful. The one for Bash is dumping only what the project actually needs.

**Comment by Sharlikran** [comment]
Ahhhhh...I think that's like when I use the asset manager to copy files, it copies vaniall assets. Zilav told me how to avoid that. I forget though. Thanks for the feedback.

**Comment by zilav** [comment]
Assets manager can skip vanilla files, but it is supported for copying assets mode only. Check vanilla archives only (or any other archives you don't want to copy files from) in `Processed containers` list and click `Build checksums`, this could take several minutes because it internally unpacks all files and calculates their checksums. This checksums index is saved into a file in xEdit folder, so you need to do that only once.

Afterwards select all containers in `Processed containers`, and in `Copy referenced assets` mode check `Skip copying files with matching checksums`. Keep in mind that script doesn't pick up implicitly used assets like facegen and voices files for example, read the description at the top of the script.

**Comment by Utumno** [comment]
Thanks for feedback everybody.

@Arthmoor - so do I have to exclude _all_ top level files? Including bsas
for instance?

**Comment by Arthmoor** [comment]
Yes, all top level files. The point of making an achlist is that you're going to ask the CK to make new BSA files for uploading. So if for some reason those are in the project folder they too need to be ignored.

**Comment by Utumno** [comment]
Thanks pushed (same branch for now, soon back to utumno-wip). 

So although you were right that

> it's simple enough to be something that can be done quickly by someone who knows how these things work

see how many details need be specified (order, top level files, help messages, games it applies etc). Start with the help message next time :P

**Comment by Utumno** [comment]
> if for some reason those are in the project folder they too need to be ignored

You certainly mean _those are meant to end up to the top level of the Data folder_ :P

**Comment by Arthmoor** [comment]
Well wherever they end up if they're at the top level they should be left out :P

Also may want to exclude the Docs folder as well since nobody will be able to access those files via Bethesda.net either.

**Comment by Utumno** [comment]
> Well wherever they end up if they're at the top level they should be left out :P

You certainly mean _wherever they are, if they end up at the top level they should be left out :P_

Docs excluded in latest iteration and readme updated (duh)
