### ISSUE TITLE
(exe version and Python 2.7.15 32-bit for python version) Wyre Bash Crash

### ISSUE THREAD

**Issue by YuliaS11** [wrye-bash/wrye-bash#424]
Traceback (most recent call last):
  File "bash\bash.py", line 321, in _main
    import bosh # this imports balt (DUH) which imports wx
  File "E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\Wrye Bash Launcher.pyw", line 76, in load_module
    exec compile(code, initfile, 'exec') in mod.__dict__
  File "bash\bosh\__init__.py", line 45, in <module>
    from ._mergeability import isPBashMergeable, isCBashMergeable
  File "E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\bosh\_mergeability.py", line 30, in <module>
    from ..load_order import cached_is_active
  File "E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\load_order.py", line 48, in <module>
    import balt
  File "E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\balt.py", line 3059, in <module>
    class WryeBashSplashScreen(wx.SplashScreen):
ImportError: caused by ImportError(u'caused by ImportError(u\'caused by ImportError(u\\\'caused by AttributeError("\\\\\\\'module\\\\\\\' object has no attribute \\\\\\\'SplashScreen\\\\\\\'",)\\\',)\',)',)

The crash report for exe version is similar with report in Nexus replies.

**Comment by Utumno** [comment]
This is an error on your setup - you should have discussed this in the forums, see the links in first page here

**Comment by awarebayes** [comment]
> see the links in the first page here
where?

**Comment by Infernio** [comment]
[See the main readme](https://github.com/wrye-bash/wrye-bash/blob/dev/Readme.md), specifically this section:

> ### Questions ? Feedback ?
> We are currently monitoring [this thread][17] at the AFK Mods forum and
> [the Wrye Bash Discord][18].
> Please be sure to ask there first before reporting an issue here. If asking for
> help please provide the info detailed in our [Reporting a bug][19] wiki page.
> In particular it is _essential_ you produce a [bashbugdump.log][20].

[17]: https://afkmods.com/index.php?/topic/4966-wrye-bash-all-games
[18]: https://discord.gg/NwWvAFR
[19]: https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug
[20]: https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug#the-bashbugdumplog
