### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by Ziktofel** [wrye-bash/wrye-bash#427]
started with:
`python Wrye\ Bash\ Launcher.pyw -o ~/Steam/steam/steamapps/common/Skyrim/`

Got error:
```
Traceback (most recent call last):
  File "bash/bash.py", line 185, in main
    _main(opts)
  File "bash/bash.py", line 360, in _main
    app.Init() # Link.Frame is set here !
  File "bash/basher/__init__.py", line 3979, in Init
    frame = BashFrame() # Link.Frame global set here
  File "bash/basher/__init__.py", line 3638, in __init__
    self.notebook = BashNotebook(self)
  File "bash/basher/__init__.py", line 3411, in __init__
    item = panel(self)
  File "bash/basher/__init__.py", line 1727, in __init__
    super(ModPanel, self).__init__(parent)
  File "bash/basher/__init__.py", line 252, in __init__
    self.detailsPanel = self._details_panel_type(self.right)
  File "bash/basher/__init__.py", line 1270, in __init__
    onText=self.OnDescrEdit, maxChars=511)
  File "bash/balt.py", line 350, in __init__
    if maxChars: self.SetMaxLength(maxChars)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 13339, in SetMaxLength
    return _core_.TextEntryBase_SetMaxLength(*args, **kwargs)
PyAssertionError: C++ assertion "IsSingleLine()" failed at ../src/gtk/textctrl.cpp(853) in GetEditable(): shouldn't be called for multiline
```

Version: current at github (dev branch)

**Comment by Ziktofel** [comment]
it's the same (using utumno-wip branch)
```
Wrye Bash encountered an error.
Please post the information below to the official thread at:
https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/& or 
https://bethesda.net/community/topic/38798/relz-wrye-bash-oblivion-skyrim-skyrim-se-fallout-4/

Traceback (most recent call last):
  File "bash/bash.py", line 185, in main
    _main(opts)
  File "bash/bash.py", line 360, in _main
    app.Init() # Link.Frame is set here !
  File "bash/basher/__init__.py", line 3986, in Init
    frame = BashFrame() # Link.Frame global set here
  File "bash/basher/__init__.py", line 3645, in __init__
    self.notebook = BashNotebook(self)
  File "bash/basher/__init__.py", line 3418, in __init__
    item = panel(self)
  File "bash/basher/__init__.py", line 1734, in __init__
    super(ModPanel, self).__init__(parent)
  File "bash/basher/__init__.py", line 252, in __init__
    self.detailsPanel = self._details_panel_type(self.right)
  File "bash/basher/__init__.py", line 1277, in __init__
    onText=self.OnDescrEdit, maxChars=511)
  File "bash/balt.py", line 350, in __init__
    if maxChars: self.SetMaxLength(maxChars)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 13339, in SetMaxLength
    return _core_.TextEntryBase_SetMaxLength(*args, **kwargs)
PyAssertionError: C++ assertion "IsSingleLine()" failed at ../src/gtk/textctrl.cpp(853) in GetEditable(): shouldn't be called for multiline
```
Maybe appears as a problem in the python wx library

**Comment by Arthmoor** [comment]
Isn't Wrye Bash only compatible with WX 2.8 though?

**Comment by Ziktofel** [comment]
Looks like 2.8 works, however, if both 2.8 and 3.0 are installed, python picks 3.0 which leads into this crash

**Comment by Infernio** [comment]
For the benefit of anyone finding this in the future: This was fixed (as in, hackily worked around) as part of moving to wxPython 3 in #15.

**Comment by Metallicow** [comment]
@Infernio 
you can specify which wxPython version you want to launch by using wx.pth file.
The old error prone wxversion.select way of doing it has been deprecated and isn't used anymore.
This is the easiest way to do this on windows.
https://github.com/Metallicow/wxpthVersionSwitcher
You should be able to figure out the rest as to how to modify it to work with PY2/3 multi wxPython installs yourself on whatever linux flavor or mac/apple install you are running.
Or bash could go and try to figure out which one to choose but that would require hotswaping on the fly and require something like this.(which might require admin privileges)
```
    if gRestartWryeBash:
        import atexit
        atexit.register(__RestartWryeBash)
```

Note: if you are a dev, the wx.pth way will probably be much easier on your patience.
