### ISSUE TITLE
[Oblivion] Problem deleting *.bak files from saves

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#442]
```
Traceback (most recent call last):
  File "bash\balt.py", line 1730, in OnItemSelected
    self._select(modName)
  File "bash\balt.py", line 1731, in _select
    def _select(self, item): self.panel.SetDetails(item)
  File "bash\basher\__init__.py", line 155, in SetDetails
    def SetDetails(self, fileName='SAME'): self._setDetails(fileName)
  File "bash\basher\__init__.py", line 153, in _setDetails
    self.detailsPanel.SetFile(fileName=fileName)
  File "bash\basher\__init__.py", line 1957, in SetFile
    self.coSaves = saveInfo.get_cosave_tags()
  File "bash\bosh\__init__.py", line 1027, in get_cosave_tags
    instances = self.get_cosave_instances()
  File "bash\bosh\__init__.py", line 1050, in get_cosave_instances
    self._co_saves = self.get_cosaves_for_path(self.getPath())
  File "bash\bosh\__init__.py", line 1061, in get_cosaves_for_path
    result[co_type] = co_type(co_path)
  File "bash\bosh\cosaves.py", line 1215, in __init__
    super(_ACosave, self).__init__(cosave_path, raise_on_error=True)
  File "bash\bosh\__init__.py", line 114, in __init__
    self._reset_cache(self._stat_tuple(), load_cache)
  File "bash\bosh\__init__.py", line 108, in _stat_tuple
    def _stat_tuple(self): return self.abs_path.size_mtime()
AttributeError: 'NoneType' object has no attribute 'size_mtime'
```

The above error occurs whenever I attempt to select a *.bak file on the saves tab. Currently using 307.201905311918 and this was never an issue with any previous version that I know of. The error window is preventing any attempt to delete these files from within Bash's UI.

**Comment by Utumno** [comment]
Does this happen on the dev branch?

**Comment by Utumno** [comment]
Ok @Arthmoor that's introduced on the nightly branch - will fix

**Comment by Utumno** [comment]
Pushed a commit on nightly that should fix that - will have to bundle an exe but I am not on windows will take couple days

**Comment by Arthmoor** [comment]
Just tried this one again but instead of the original error, I'm getting a different one now:

![OBSaves](https://user-images.githubusercontent.com/1762652/71927210-384ef780-3152-11ea-858c-2ed7777a214b.png)

**Comment by Utumno** [comment]
Good catch will fix - this is on delete right?

**Comment by Arthmoor** [comment]
Yes, that was when deleting a .bak file.
