### ISSUE TITLE
Install Wizard: Break causes error if on same flow control level as While

### ISSUE THREAD

**Issue by alphaniner** [wrye-bash/wrye-bash#445]
The following While loop throws an error when the `Break` is encountered:
```
While True
	continue = 0
	If continue == 1
		Continue
	EndIf
	Break
EndWhile
```

Error:
```
An unhandled error occurred while parsing the wizard:
Line 6:		Break

Traceback (most recent call last):
  File "bash\belt.py", line 927, in Continue
    self.RunLine(newline)
  File "bash\ScriptParser.py", line 502, in RunLine
    key(*self.tokens)
  File "bash\ScriptParser.py", line 367, in __call__
    def __call__(self, *args, **kwdargs): return self.tkn(*args, **kwdargs)
  File "bash\ScriptParser.py", line 294, in __call__
    return self.execute(*args)
  File "bash\ScriptParser.py", line 259, in execute
    return self.function(*args)
  File "bash\belt.py", line 1487, in kwdBreak
    flow.active = False
UnboundLocalError: local variable 'flow' referenced before assignment
```
The problem is that `flow` doesn't get assigned if `Break` is on the same flow control level as the `While` it's associated with (Mopy/bash/belt.py lines 1485-1486):
```
            while self.LenFlow() > index+1:
                flow = self.PopFlow()
```
Replacing that with the means of assignment used in the definition of `Continue` (lines 1272-1274) resolves the issue:
```
            while self.LenFlow() > index+1:
                self.PopFlow()
            flow = self.PeekFlow()
```

**Comment by alphaniner** [comment]
Also, I noticed a typo on line 1253 when looking into this:
```
self.PushFlow('While', False, [u'While', u'EndWhile'])
```
That first `'While'` should be `u'While'`

**Comment by Infernio** [comment]
Thanks for the detailed bug report, should be fixed as of https://github.com/wrye-bash/wrye-bash/commit/c8412e8566ab0123edf27e684fa097931361134c.
