### ISSUE TITLE
Wrye Bash fails to load for Skyrim SE

### ISSUE THREAD

**Issue by the-aon** [wrye-bash/wrye-bash#453]
I wouldn't doubt it if this issue has been presented and resolved a dozen times already...but I'll be damned if I can find it.

I've got Wrye Bash installed for FO4, Skyrim LE and Skyrim SE. It still works for the first two, but one day, it stopped loading for Skyrim SE. I've re-installed Wrye Bash multiple times, tried the SA version, even disabled all the mods in NMM- all to no avail. This is particularly vexing because it has put the kibosh on the modding I was doing for the game.

Here is the issue:
1. I start Wrye Bash for Skyrim SE. 2. Wrye Bash does not start, but fails with this error:

Wrye Bash encountered an error.
Please post the information below to the official thread at:
https://afkmods.com/index.php?/topic/4966-wrye-bash-all-games/& or 
https://bethesda.net/community/topic/38798/relz-wrye-bash-oblivion-skyrim-skyrim-se-fallout-4/

Traceback (most recent call last):
  File "bash\bash.pyo", line 227, in main
  File "bash\bash.pyo", line 393, in _main
  File "bash\basher\__init__.pyo", line 3981, in Init
  File "bash\basher\__init__.pyo", line 4021, in InitData
  File "bash\bosh\__init__.pyo", line 2726, in refresh
  File "bash\bosh\__init__.pyo", line 1382, in refresh
  File "bash\bosh\__init__.pyo", line 1358, in new_info
  File "bash\bosh\__init__.pyo", line 1277, in new_info
  File "bash\bosh\__init__.pyo", line 393, in __init__
  File "bash\bosh\__init__.pyo", line 274, in __init__
  File "bash\bosh\__init__.pyo", line 405, in _reset_cache
  File "bash\bosh\__init__.pyo", line 1108, in readHeader
  File "bash\bosh\save_headers.pyo", line 62, in __init__
  File "bash\bosh\save_headers.pyo", line 78, in load_header
  File "bash\bosh\save_headers.pyo", line 228, in load_image_data
  File "bash\bosh\save_headers.pyo", line 96, in _drop_alpha
MemoryError

Other details:
I've tried a few versions of the program, most recently the latest version downloaded from the Nexus SE page.

Until a couple of months ago, the program worked without issue. (there have been a few updates to Win 10, Steam, etc in that time)

I do use SKSE, in case that matters.

If there is anything else you need to know, please let me know.

**Comment by Utumno** [comment]
maybe too many saves? try moving some of your saves to a backup folder

**Comment by the-aon** [comment]
> maybe too many saves? try moving some of your saves to a backup folder

You have got to be kidding me. That solved it. Thank you for pointing out the (now) glaringly obvious!

**Comment by Infernio** [comment]
Now entirely obsolete as of 308 (64bit upgrade).
