### ISSUE TITLE
Error on Startup: Invalid Load Key

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#455]
Reported on Discord:
```
Traceback (most recent call last):
  File "bash\bash.pyo", line 184, in main
  File "bash\bash.pyo", line 362, in _main
  File "bash\basher\__init__.pyo", line 4029, in Init
  File "bash\basher\__init__.pyo", line 4066, in InitData
  File "bash\bosh\__init__.pyo", line 1902, in refresh
  File "bash\bosh\__init__.pyo", line 1649, in _modinfos_cache_wrapper
  File "bash\bosh\__init__.pyo", line 1757, in refreshLoadOrder
  File "bash\load_order.pyo", line 286, in refresh_lo
  File "bash\load_order.pyo", line 313, in __load_pickled_load_orders
  File "bash\bolt.pyo", line 1514, in load
UnpicklingError: invalid load key, ''.
```
(the invalid load key is an ASCII escape character, 0x1B)

Full bugdump: https://gist.github.com/Infernio/cdd3ce98c1e24e06ffb7fe60c687bb8b

**Comment by Infernio** [comment]
Can't reproduce it ATM, opened this to let @Utumno know.

**Comment by Utumno** [comment]
We would need the BashLoadOrder.dat I guess, not sure how this ended up there

**Comment by Infernio** [comment]
The user got back to me and uploaded their [BashLoadOrders.dat](https://github.com/wrye-bash/wrye-bash/files/3561220/BashLoadOrders.dat.zip).
A simple `pickle.load(open(u'BashLoadOrders.dat'))` reproduces it, seems that the file got corrupted somehow?

**Comment by Infernio** [comment]
I asked them to rename their `BashLoadOrders.dat` to `BashLoadOrders.dat.old` (and the `.bak` too). That allowed them to launch again, and it hasn't happened again since. I'm leaning towards this being some random data corruption - failing hard drive, cosmic ray, unstable CPU overclock, whatever other reason you can come up with for random bit flips 😛

**Comment by Utumno** [comment]
Let's reopen as needed then!

**Comment by Infernio** [comment]
Someone else got a pickle error when loading `BashLoadOrders.dat` too, different error though:
```
Traceback (most recent call last):
  File "bash\bash.pyo", line 188, in main
  File "bash\bash.pyo", line 372, in _main
  File "bash\basher__init.pyo", line 4050, in Init
  File "bash\basher__init.pyo", line 4087, in InitData
  File "bash\bosh__init.pyo", line 1936, in refresh
  File "bash\bosh__init.pyo", line 1683, in _modinfos_cache_wrapper
  File "bash\bosh__init.pyo", line 1791, in refreshLoadOrder
  File "bash\load_order.pyo", line 286, in refresh_lo
  File "bash\load_order.pyo", line 313, in load_pickled_load_orders
  File "bash\bolt.pyo", line 1524, in load
BadPickleGet: 0
```
Just posting this here for potential future reference, I'm leaning towards both of these just being data corruption.

**Comment by Infernio** [comment]
@Utumno Here's a weird startup crash reported on Discord: https://gist.github.com/Infernio/06f96001a5f1472a0475769a16312cf9
I asked the user to rename their BashSettings files so that new ones would be created, but it still happened. No idea what's causing it.

**Comment by Utumno** [comment]
Hmmm - they probably did not rename the bak - it's impossible to hit that if no files are present. Ask them to remove both files. But yes there is something fishy - hopefully not the active load order setting.

Does it happen on dev?

Anyway the files failed to load - if they could send us those over to have a look?

Maybe we should package a dev build also to have people easily test the standalone on dev

**Comment by Infernio** [comment]
Looks like this may have been reported a few times in the past, with a variety of binary files as the 'culprit':
 - https://www.afkmods.com/index.php?/topic/4966-wrye-bash-all-games/page/79/&tab=comments#comment-175740
 - https://forums.nexusmods.com/index.php?/topic/5213770-wrye-bash/page-98#entry70525638
 - https://github.com/Wrye-Code-Collection/wrye-bash/issues/8

Not sure how many of those are actually the same error though.
