### ISSUE TITLE
Can't start wyre bash

### ISSUE THREAD

**Issue by 3baady** [wrye-bash/wrye-bash#504]
This error comes up : 

Traceback (most recent call last):
  File "bash\bash.pyo", line 184, in main
  File "bash\bash.pyo", line 362, in _main
  File "bash\basher\__init__.pyo", line 4029, in Init
  File "bash\basher\__init__.pyo", line 4068, in InitData
  File "bash\bosh\__init__.pyo", line 2683, in __init__
  File "bash\bosh\__init__.pyo", line 1208, in __init__
  File "bash\bosh\__init__.pyo", line 1290, in _initDB
  File "bash\bosh\__init__.pyo", line 1198, in _initDB
  File "bash\bolt.pyo", line 915, in makedirs
  File "os.pyo", line 150, in makedirs
  File "os.pyo", line 150, in makedirs
  File "os.pyo", line 150, in makedirs
  File "os.pyo", line 150, in makedirs
  File "os.pyo", line 157, in makedirs
WindowsError: [Error 3] The system cannot find the path specified: u'N:\\'

**Comment by Infernio** [comment]
Discussed on Discord.
