### ISSUE TITLE
Regressions due to tweak pooling

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#541]
Opening this to collect regressions from tweak pooling. I won't have time to fix them for the next couple weeks, but this way they won't get lost in a sea of Discord comments.

- [ ] The "Robes Show Pants" tweak is currently removing the "Lower Body" flag from all clothes…including pants.
- [ ] Globals tweaks now only log if they actually changed something, which can be confusing (gives no feedback if the tweak was actually enabled).
- [ ] The 'Armor' and 'Clothes' name tweaks aren't correctly renaming pants.
- [ ] `SNDX` is not getting written out if the attenuation tweaks make an entire subrecord == 0. xEdit makes this subrecord required, so we should too.
- [ ] Reweigh Potions/Ingestibles is not working as intended (putting the wrong weights into the BP).
- [ ] This:
```
Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 172, in PatchExecute
    patchFile.scanLoadMods(SubProgress(progress,0.2,0.8)) #try to speed this up!
  File "bash\patcher\patch_files.py", line 245, in scanLoadMods
    patcher.scan_mod_file(modFile,nullProgress)
  File "bash\patcher\base.py", line 79, in scan_mod_file
    self.scanModFile(modFile, progress)
  File "bash\patcher\patchers\base.py", line 127, in scanModFile
    if p_tweak.wants_record(record):
  File "bash\patcher\patchers\multitweak_names.py", line 95, in wants_record
    self._try_renaming(record))
  File "bash\patcher\patchers\multitweak_names.py", line 77, in _try_renaming
    return record.full != self._exec_rename(record)
  File "bash\patcher\patchers\multitweak_names.py", line 61, in _exec_rename
    return self._do_exec_rename(*self._get_rename_params(record))
  File "bash\patcher\patchers\multitweak_names.py", line 213, in _do_exec_rename
    wip_name = _re_old_potion_label.sub(u'', record.full)
TypeError: expected string or buffer

Traceback (most recent call last):
  File "bash\gui\events.py", line 165, in _post
    result = listener(*listener_args)
  File "bash\balt.py", line 871, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\patcher_dialog.py", line 172, in PatchExecute
    patchFile.scanLoadMods(SubProgress(progress,0.2,0.8)) #try to speed this up!
  File "bash\patcher\patch_files.py", line 245, in scanLoadMods
    patcher.scan_mod_file(modFile,nullProgress)
  File "bash\patcher\base.py", line 79, in scan_mod_file
    self.scanModFile(modFile, progress)
  File "bash\patcher\patchers\base.py", line 127, in scanModFile
    if p_tweak.wants_record(record):
  File "bash\patcher\patchers\multitweak_names.py", line 95, in wants_record
    self._try_renaming(record))
  File "bash\patcher\patchers\multitweak_names.py", line 77, in _try_renaming
    return record.full != self._exec_rename(record)
  File "bash\patcher\patchers\multitweak_names.py", line 61, in _exec_rename
    return self._do_exec_rename(*self._get_rename_params(record))
  File "bash\patcher\patchers\multitweak_names.py", line 213, in _do_exec_rename
    wip_name = _re_old_potion_label.sub(u'', record.full)
TypeError: expected string or buffer
```
- [x] Reweigh tweaks blow up when activated outside Oblivion. -> 3e7a89b4f634e62bad81da6c29117e289b7217ff
- [x] Reweigh: Ingestibles (Minimum) isn't running at all. -> 3e7a89b4f634e62bad81da6c29117e289b7217ff

**Comment by Infernio** [comment]
Lord Nyriox:
> The "Robes Show Pants" tweak is currently removing the "Lower Body" flag from all clothes…including pants. 
>
> As amusing as it is to see every unarmored NPC walking around in his or her underwear, I sincerely doubt that is intended behavior.  :laughing:

**Comment by Utumno** [comment]
I knew this issue would pop up :P - come next week I may be able to give a hand, real busy with RL here too. However got to rebasing pt3, there are some things I need to grok (like FixedString) and frankly, the codebase feels strange without all the cruft I was grepping through :P but will have the rebase finished soon.
