### ISSUE TITLE
Fails to execute with -o parameter

### ISSUE THREAD

**Issue by 13gears13** [wrye-bash/wrye-bash#671]
Traceback (most recent call last):
  File "argparse.py", line 1902, in parse_known_args
  File "argparse.py", line 2114, in _parse_known_args
  File "argparse.py", line 2044, in consume_optional
  File "argparse.py", line 2208, in _match_argument
argparse.ArgumentError: argument -o/--oblivionPath: expected one argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 29, in <module>
  File "bash\barg.py", line 126, in parse
  File "argparse.py", line 1869, in parse_args
  File "argparse.py", line 1904, in parse_known_args
  File "argparse.py", line 2626, in error
  File "argparse.py", line 2596, in print_usage
  File "argparse.py", line 2607, in _print_message
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by sibir-ine** [comment]
You should report issues to the AFK Mods thread or WB Discord before posting issues here (see this repo's [readme](https://github.com/wrye-bash/wrye-bash#questions--feedback-)). What's the exact argument you passed WB?

**Comment by Infernio** [comment]
Looks like you're missing the argument to `-o`, e.g. `-o "G:\My Games\Oblivion"`. See the [command line argument documentation](https://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#tools-arguments).

And like sibir said, please report to the AFKMods thread or the Discord first so we don't use an issue for regular reports.
