### ISSUE TITLE
Exception in 313 Nightly

### ISSUE THREAD

**Issue by AndalayBay** [wrye-bash/wrye-bash#678]
Getting this when uninstalling a package:
`Traceback (most recent call last):
  File "bash\bolt.py", line 534, in __new__
KeyError: bolt.Path('C:\\Games\\Oblivion\\Data\\beeratcompil_nordbarbare.esm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bash\balt.py", line 1688, in __Execute
  File "bash\balt.py", line 515, in _conversation_wrapper
  File "bash\basher\installer_links.py", line 889, in Execute
  File "bash\bosh\bain.py", line 2772, in bain_uninstall
  File "bash\bosh\bain.py", line 2804, in _do_uninstall
  File "bash\bosh\bain.py", line 2811, in _remove_restore
  File "bash\bosh\bain.py", line 2732, in _removeFiles
  File "bash\bosh\__init__.py", line 1533, in delete
  File "bash\bosh\__init__.py", line 3233, in delete_refresh
  File "bash\bosh\__init__.py", line 1815, in delete_refresh
  File "bash\bosh\__init__.py", line 1709, in delete_refresh
  File "bash\bolt.py", line 1610, in __getitem__
  File "bash\bolt.py", line 677, in __getitem__
  File "bash\bolt.py", line 537, in __new__
ValueError: bolt.Path('C:\\Games\\Oblivion\\Data\\beeratcompil_nordbarbare.esm') type is <class 'bash.bolt.Path'> - a str is required
`
I've had it pop up a couple of times now with different packages.

**Comment by Utumno** [comment]
Please post to Discord first, these are regressions from bleeding edge development - this should be fixed in current nightly

**Comment by AndalayBay** [comment]
I have and have never gotten a response. Understood regarding the nightlies. I won't report in the future.

**Comment by Infernio** [comment]
Just ask again in that case. You can also feel free to ping @Developers on there if you've asked before and no one responded.

**Comment by Utumno** [comment]
> I have and have never gotten a response. Understood regarding the nightlies. I won't report in the future.

This probably meant we had no time - this particular one was already commented discussed: https://discord.com/channels/537706885965676554/537710082755133460/1204477501859172362

Reports on nightly are of course needed but *on Discord*

**Comment by AndalayBay** [comment]
There have been several. Anyway I hate Discord, so I won't worry about reporting nightlies. It's super rare that I grab nightlies anyway, so no loss.
