### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'description'

### ISSUE THREAD

**Issue by badgerbadgerdroid** [wrye-bash/wrye-bash#689]
### Latest Nightly
- [ X] I have tried the latest nightly build and the issue still occurs.

### Asking on Discord/AFKMods

- [ X] I have asked on Discord/AFKMods and posted as requested by Utumno

### BashBugDump

[BashBugDump.log](https://github.com/user-attachments/files/18135905/BashBugDump.log)

### Details of the Issue

![image (1)](https://github.com/user-attachments/assets/da1ba2e0-7b53-4bb3-a593-9eb1bce63a64)

#### Description
Replace this section with a description of the issue. Describe what you wanted
the program to do and what it did instead.

#### Step-by-step reproduction

Attempting to launch Wryebash causes the above error, even old versions that previously did work (12.1). 

The only common theme I found was the affected devices were my 2 Laptops which had upgraded to 24H2 Windows 11 upgrade recently. 
The same mod list on my other devices one Windows 10 and one Windows 11 23H2 both allowed Wryebash to launch successfully. 

(This is launched through MO2 using a stock game install inside the MO2 folder for Fallout 4)

**Comment by badgerbadgerdroid** [comment]
![Screenshot 2024-12-16 051857](https://github.com/user-attachments/assets/84cfe15f-0477-4777-907c-409a77328af2)
Under Win 11 24-H2

**Comment by Utumno** [comment]
Forget about that - I was overeager to propagate the FileNotFound error

**Comment by badgerbadgerdroid** [comment]
[BashBugDump.log](https://github.com/user-attachments/files/18154144/BashBugDump.log)
Latest build error

**Comment by Utumno** [comment]
See comment by Arthmoor here: https://discord.com/channels/537706885965676554/537710082755133460/1318342683130859582

Seems 24h2 broke virtual filesystems (and more) - well this much was clear but now we have confirmation.

An other probably unrelated error is when loading table.dat for ModInfos:


```
__init__.py 1576 _init_store: Initializing ModInfos
__init__.py 1577 _init_store:  store_dir: G:\SteamLibrary\steamapps\common\Skyrim Special Edition AE\Data
__init__.py 1723 _init_from_table:  bash_dir: G:\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data
Wrye Bash encountered an error. Please post the information below as well as your BashBugDump to the official thread at https://afkmods.com/index.php?/topic/4966-wrye-bash-all-games or to the Wrye Bash Discord at https://discord.gg/NwWvAFR

Traceback (most recent call last):
  File "bash\bash.py", line 524, in main
  File "bash\bash.py", line 692, in _main
  File "bash\basher\__init__.py", line 4193, in Init
  File "bash\bosh\__init__.py", line 3515, in init_stores
  File "bash\bosh\__init__.py", line 2095, in __init__
  File "bash\bosh\__init__.py", line 1571, in __init__
  File "bash\bosh\__init__.py", line 2257, in refresh
  File "bash\bosh\__init__.py", line 1731, in refresh
  File "bash\bosh\__init__.py", line 1725, in _init_from_table
  File "bash\bolt.py", line 2133, in __init__
  File "bash\bolt.py", line 1893, in __init__
  File "bash\bolt.py", line 1942, in load
  File "bash\bolt.py", line 1925, in _perform_load
TypeError: 'str' object is not callable
```

**Comment by Infernio** [comment]
To be tackled further in 314, for 313 the advice is "don't use 24H2".
