### ISSUE TITLE
Error on re-enabling disabled save master

### ISSUE THREAD

**Issue by Ortham** [wrye-bash/wrye-bash#9]
Traceback is

```
Traceback (most recent call last):
  File "bash\basher.py", line 1385, in DoItemMenu
    self.OnLeftDown(event)
  File "bash\basher.py", line 1399, in OnLeftDown
    if not balt.askContinue(self,message,'bash.masters.update',_(u'Update Masters')):
  File "bash\balt.py", line 410, in askContinue
    heading=u'',
  File "bash\balt.py", line 592, in vistaDialog
    result = dialog.show(commandLinks)
  File "bash\windows.py", line 494, in show
    indirect(byref(conf), byref(button), byref(radio), byref(checkbox))
WindowsError: exception: access violation reading 0x00000018
```

**Comment by Infernio** [comment]
Please comment / reopen if this can be reproduced again.
